import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar.component";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({children}: Readonly<{children: React.ReactNode;}>) {
    const cookieStore = await cookies();
    const token = cookieStore.get("__session")?.value;
    return (
        <>
            <Navbar loggedIn={token ? true : false} />
            {children}
        </>
    );
}
