import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar.component";
import { cookies } from "next/headers";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Project - Velox Search",
  description: "Generated by create next app",
};

export default async function DashboardLayout({children}: Readonly<{children: React.ReactNode;}>) {
    const cookieStore = await cookies();
    const token = cookieStore.get("__session")?.value;
    return (
        <>
            <Suspense fallback={<div>Loading...</div>}>
                <Navbar />
            </Suspense>
            {children}
        </>
    );
}
