import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/SIdebar/Sidebar.component";

export const metadata: Metadata = {
  title: "Project - Velox Search",
  description: "Generated by create next app",
};

export default async function ProjectLayout({children}: Readonly<{children: React.ReactNode;}>) {
    return (
        <div style={{display: "flex", gap: "1rem"}}>  
            <Sidebar />
            {children}
        </div>
    );
}
