import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar.component";

export const metadata: Metadata = {
  title: "Dashboard | VeloxSearch",
  description: "Generated by create next app",
};

export default async function DashboardLayout({children}: Readonly<{children: React.ReactNode;}>) {
    return (
        <>
            <Navbar/>
            {children}
        </>
    );
}
